### ISSUE TITLE
How to add a new CPU architecture ?

### ISSUE THREAD

**Issue by shushanhf** [AngelDE98/MonoMod#120]
Now the MonoMod only supports the ARM32/64 X86/64,
if running on LoongArch64 linux, the MonoMod.Common will hit errors liking the FlushCache.

I want to know how add a new CPU architecture and how to testing.
The master branch is not only supporting the SDK5.0.17 and how to build by SDK6.0 or SDK7.0 ?

**Comment by nike4613** [comment]
Active development is currently only happening on the `reorganize` branch, which we should be merging back to master hopefully fairly soon. (This is currently available on NuGet as `MonoModReorg.{Core,RuntimeDetour}`.)

Within `reorganize`, the general procedure will be:
1. Update `src/MonoMod.Utils/PlatformDetection.cs` to be able to recognize the architecture from the `uname()` output
2. Create a new implementation of `MonoMod.Core.Platforms.IArchitecture` in `src/MonoMod.Core/Platforms/Architectures/` for the architecture
   - The existing x86-based implementations should give a decent overview of what all is needed. Some of the stubs that we use aren't very well commented, but correspond to labels in `x86_64/stubs_x86_64.asm` where some of them are described in more detail. Also look at the documentation on `IArchitecture` for the description of some of them.
   - The alternate entrypoint factory is optional, though would be nice, because it allows detours of native functions to call back to the original. 
3. Update `MonoMod.Core.Platforms.PlatformTriple` to recognize and construct the architecture implementation in `CreateCurrentArchitecture` 
4. Update the `ISystem` implementations for the operating systems that it will be running on (`src/MonoMod.Core/Platforms/Systems/`) to recognize the architecture and select the correct ABI for it
   - The ABI classifier currently only needs to be able to correctly classify return types to determine when a return buffer is needed, however it will in the future need to be able to recognize when an argument is potentially passed in-register, by reference, or on the stack. 
   - The `ArgumentOrder` should be the *native* argument order, as it is up to the `IRuntime` implementation to update that ABI to reflect the actual managed ABI. 
5. Update the appropriate `IRuntime` implementation (likely `CoreBaseRuntime`) to be able to recognize the architecture, and ensure that it defines the correct argument order for it
6. If targeting Linux or MacOS, you'll need to implement a native exception helper for your architecture, and update those runtimes to load it correctly. (Note that the native exception helper is currently incomplete for MacOS; that's my current project.)
   - The Linux (and future Mac) native exception helper are defined as NASM assembly files in `src/MonoMod.Core/Platforms/Architectures/x86_64/`, and export an `eh_get_exception_ptr` (which gets a pointer to the TLS cell used to hold the exception pointer), `eh_managed_to_native`, which uses the architecture's special entry ABI (on x86_64, pass jump target in `rax`) to call a native function which may throw, catches any exceptions and stashes them in the TLS cell, and `eh_native_to_managed` which does the same thing, except its target should be a reverse-P/Invoke stub and, when it returns, it throws the exception in the TLS cell if present.
   - This is required to prevent runtime hard-crashes for invalid IL (i.e. when the JIT throws through our hook)

I believe that should be all you'd need to touch for it to work. If the runtime has different object layouts on this architecture, however, there are a few other places that need to be updated, though I doubt that that will be a problem.

The `reorganize` branch also has a `docs` folder which contains some documentation on this, though not in all that much detail. Nonetheless, it is likely a good place to look first. Of course, I will answer any other specific questions.

**Comment by shushanhf** [comment]
@nike4613 
Thanks very much!
