### ISSUE TITLE
Adding System.Buffers and MonoMod.Backports simultaneously in net48 project causes Error CS0433

### ISSUE THREAD

**Issue by zabulus** [AngelDE98/MonoMod#146]
### Description
Basically everything is described in subject. Project for netfw 48 with System.Buffers and MonoMod.Backports dependencies causes error:
```0>Program.cs(4,12): Error CS0433 : The type 'ArrayPool<T>' exists in both 'MonoMod.Backports, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null' and 'System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'```

### Minimal repro.

```cs
using System.Buffers;

var pool = ArrayPool<byte>.Shared; 

Console.WriteLine("Hello, World!");

```
csproj file
```csproj
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net48</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MonoMod.Backports" Version="1.0.1" />
      <PackageReference Include="System.Buffers" Version="4.5.1" />
    </ItemGroup>

</Project>

```
I think that for net45+ no need to include ArrayPool into Backports, reference to System.Buffers is sufficient.

**Comment by nike4613** [comment]
If you look at the description of #151, you can see some of the reason why.

Notably, the implementations Backports includes are newer, and generally more performant, than the ones from the OOB packages. The only places where that's not the case is when they are inbox, and for those, Backports already forwards to them correctly. Also, unlike the OOB packages, the implementations in Backports stand more than a snowball's chance in hell of being updated.

There are also some issues around getting sane builds using the OOB packages, which I frankly have no idea how to fix. 

That PR *does* switch to using the `System.ValueTuple` OOB package, when possible, because it presents no actual issues, and exposes an identical API surface to the newer implementation in Backports. Very little has changed in their implementation since they were introduced that does not require runtime-specific considerations.

The supported mechanism to deal with this problem in general is the [`Aliases` metadata on `PackageReference` items](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#packagereference-aliases). This enables the project to refer to the types from each package independently. I obviously recommend preferring the Backports-exported implementations where possible.

**Comment by zabulus** [comment]
Ok, makes sense. But maybe you could make them internal that they won't pollute dependent projects?

**Comment by nike4613** [comment]
That kinda defeats the point. Backports is intended as a *replacement* for the OOB packages, that enables using their types (and then some) on older runtimes.

**Comment by zabulus** [comment]
Ah, I see. Okay, will try to resolve this using aliases.
